name = "efeindonesia-redirect"
main = "worker.js"
compatibility_date = "2023-08-15"

# Replace with your account ID from Cloudflare dashboard
account_id = "0c2c50292fb965e67e1b3a9997a3fc88"

# Define the route for your worker
routes = [
  { pattern = "efeindonesia.id/*", zone_name = "efeindonesia.id" }
]